<?xml version="1.0"?>
<project
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.jaime.kogito.tests</groupId>
  <artifactId>kogito-bpmn-app-unsecured</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <properties>
    <compiler-plugin.version>3.10.1</compiler-plugin.version>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <surefire-plugin.version>3.0.0-M7</surefire-plugin.version>
    <maven.enforcer.plugin.version>3.5.0</maven.enforcer.plugin.version>
    <version.logging-manager.quarkus>3.1.2</version.logging-manager.quarkus>
    <micrometer.version>3.2.4</micrometer.version>
    <bamoe.build>bamoe-community</bamoe.build>
  </properties>

  <dependencies>
    <!-- Application-specific dependencies
    <dependency>
      <groupId>org.jaime.kogito.tests</groupId>
      <artifactId>kogito-bpmn-custom-user-task-lifecycle</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>org.jaime.kogito.tests</groupId>
      <artifactId>kogito-bpmn-custom-user-task-event-listener</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
    -->

    <!-- jBPM and Drools -->
    <dependency>
      <groupId>org.jbpm</groupId>
      <artifactId>jbpm-with-drools-quarkus</artifactId>
    </dependency>

    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>process-workitems</artifactId>
    </dependency>

    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-decisiontables</artifactId>
    </dependency>

    <!-- Addons to include management endpoints in the Kogito app -->
    <dependency>
      <groupId>org.kie</groupId>
      <artifactId>kie-addons-quarkus-process-management</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kie</groupId>
      <artifactId>kie-addons-quarkus-process-svg</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kie</groupId>
      <artifactId>kie-addons-quarkus-source-files</artifactId>
    </dependency>

    <!-- Logging -->
    <dependency>
      <groupId>io.quarkiverse.loggingmanager</groupId>
      <artifactId>quarkus-logging-manager</artifactId>
      <version>${version.logging-manager.quarkus}</version>
    </dependency>

    <!-- RESTEasy Classic
     -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-client-jackson</artifactId>
    </dependency>

    <!-- Others -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5-mockito</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>bamoe-enterprise</id>
      <activation>
        <property>
          <name>bamoe.build</name>
          <value>bamoe-enterprise</value>
        </property>
        <activeByDefault>true</activeByDefault>
      </activation>

      <repositories>
        <repository>
          <id>ibm-bamoe-enterprise-maven-repository</id>
          <url>http://localhost:8800</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>
      </repositories>

      <pluginRepositories>
        <pluginRepository>
          <id>ibm-bamoe-enterprise-maven-repository</id>
          <url>http://localhost:8800</url>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>

      <properties>
        <!--
        <quarkus.platform.group-id>com.redhat.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.version>3.8.6.SP1-redhat-00002</quarkus.platform.version>
        <quarkus-plugin.version>3.8.6.SP1-redhat-00002</quarkus-plugin.version>
        -->
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
        <quarkus.platform.version>3.15.4</quarkus.platform.version>
        <bamoe.bom.group-id>com.ibm.bamoe</bamoe.bom.group-id>
        <bamoe.bom.artifact-id>bamoe-bom</bamoe.bom.artifact-id>
        <version.org.kie.kogito>9.2.0-ibm-0004</version.org.kie.kogito>
        <version.org.jbpm.quarkus.devui>9.2.0-ibm-0004</version.org.jbpm.quarkus.devui>
      </properties>

      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>${quarkus.platform.group-id}</groupId>
            <artifactId>${quarkus.platform.artifact-id}</artifactId>
            <version>${quarkus.platform.version}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
          <dependency>
            <groupId>${bamoe.bom.group-id}</groupId>
            <artifactId>${bamoe.bom.artifact-id}</artifactId>
            <version>${version.org.kie.kogito}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
          <dependency>
            <groupId>${bamoe.bom.group-id}</groupId>
            <artifactId>bamoe-techpreview-bom</artifactId>
            <version>${version.org.kie.kogito}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
          <dependency>
            <groupId>org.drools</groupId>
            <artifactId>drools-bom</artifactId>
            <version>${version.org.kie.kogito}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
        </dependencies>
      </dependencyManagement>
    </profile>

    <profile>
      <id>bamoe-community</id>
      <activation>
        <property>
          <name>bamoe.build</name>
          <value>bamoe-community</value>
        </property>
      </activation>
      <repositories>
        <repository>
          <id>apache-public-repository-group</id>
          <name>Apache Public Repository Group</name>
          <url>https://repository.apache.org/content/groups/public/</url>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
          </snapshots>
        </repository>
      </repositories>

      <pluginRepositories>
        <pluginRepository>
          <id>apache-public-repository-group</id>
          <name>Apache Public Repository Group</name>
          <url>https://repository.apache.org/content/groups/public/</url>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>daily</updatePolicy>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>

      <properties>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
        <!--
        -->
        <quarkus.platform.version>3.15.4</quarkus.platform.version>
        <version.org.kie.kogito>999-SNAPSHOT</version.org.kie.kogito>
        <!--
        <quarkus.platform.version>3.8.6.1</quarkus.platform.version>
        <kogito.version>999-20250126-SNAPSHOT</kogito.version>
        -->
        <!--
        <quarkus.platform.version>3.8.6.1</quarkus.platform.version>
        <kogito.version>10.0.0</kogito.version>
        -->
        <kogito.bom.group-id>org.kie.kogito</kogito.bom.group-id>
        <kogito.bom.artifact-id>kogito-bom</kogito.bom.artifact-id>
        <kogito-apps.bom.artifact-id>kogito-apps-bom</kogito-apps.bom.artifact-id>
        <version.org.jbpm.quarkus.devui>999-SNAPSHOT</version.org.jbpm.quarkus.devui>
      </properties>

      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>${quarkus.platform.group-id}</groupId>
            <artifactId>${quarkus.platform.artifact-id}</artifactId>
            <version>${quarkus.platform.version}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
          <dependency>
            <groupId>${kogito.bom.group-id}</groupId>
            <artifactId>${kogito.bom.artifact-id}</artifactId>
            <version>${version.org.kie.kogito}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
          <dependency>
            <groupId>${kogito.bom.group-id}</groupId>
            <artifactId>${kogito-apps.bom.artifact-id}</artifactId>
            <version>${version.org.kie.kogito}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
          <dependency>
            <groupId>org.kie.kogito</groupId>
            <artifactId>kogito-kie-bom</artifactId>
            <version>${version.org.kie.kogito}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
          <dependency>
            <groupId>org.drools</groupId>
            <artifactId>drools-bom</artifactId>
            <version>${version.org.kie.kogito}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
        </dependencies>
      </dependencyManagement>
    </profile>

    <profile>
      <id>development</id>
      <properties>
        <quarkus.profile>dev</quarkus.profile>
        <quarkus.wiremock.version>1.3.3</quarkus.wiremock.version>
      </properties>
      <!--
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>org.jbpm</groupId>
            <artifactId>jbpm-quarkus-devui-bom</artifactId>
            <version>${version.org.jbpm.quarkus.devui}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
        </dependencies>
      </dependencyManagement>
      -->
      <dependencies>
        <!--
        -->
        <dependency>
          <groupId>org.jbpm</groupId>
          <artifactId>jbpm-quarkus-devui</artifactId>
          <version>${version.org.jbpm.quarkus.devui}</version>
        </dependency>
        <dependency>
          <groupId>io.quarkiverse.wiremock</groupId>
          <artifactId>quarkus-wiremock</artifactId>
          <version>${quarkus.wiremock.version}</version>
        </dependency>
        <!--
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-jdbc-h2</artifactId>
        </dependency>
        -->
      </dependencies>
    </profile>

    <profile>
      <id>embedded-postgresql</id>
      <properties>
        <quarkus.embedded.postgresql.version>0.3.1</quarkus.embedded.postgresql.version>
      </properties>
      <dependencies>
        <dependency>
          <groupId>io.quarkiverse.embedded.postgresql</groupId>
          <artifactId>quarkus-embedded-postgresql</artifactId>
          <version>${quarkus.embedded.postgresql.version}</version>
        </dependency>
      </dependencies>
    </profile>

    <profile>
      <id>bamoe-persistence-postgresql</id>
      <dependencies>
        <!-- Persistence -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kie-addons-quarkus-persistence-jdbc</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-jdbc-postgresql</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-agroal</artifactId>
        </dependency>
        <!-- Data Index Addon -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kogito-addons-quarkus-data-index-postgresql</artifactId>
        </dependency>
        <!-- User Tasks -->
        <dependency>
          <groupId>org.jbpm</groupId>
          <artifactId>jbpm-addons-quarkus-usertask-storage-jpa</artifactId>
        </dependency>
        <!-- Jobs Service -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kogito-addons-quarkus-jobs</artifactId>
        </dependency>
        <dependency>
          <groupId>org.kie.kogito</groupId>
          <artifactId>jobs-service-storage-jpa</artifactId>
        </dependency>
        <!-- Jobs Management endpoints -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kogito-addons-quarkus-jobs-management</artifactId>
        </dependency>
      </dependencies>
    </profile>

    <profile>
      <id>bamoe-persistence-inmemory</id>
      <dependencies>
        <!-- Data Index Addon -->
        <dependency>
          <groupId>org.kie.kogito</groupId>
          <artifactId>kogito-addons-quarkus-data-index-inmemory</artifactId>
          <version>${version.org.kie.kogito}</version>
        </dependency>
        <!-- Jobs Service -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kogito-addons-quarkus-jobs-service-embedded</artifactId>
        </dependency>
        <dependency>
          <groupId>org.kie.kogito</groupId>
          <artifactId>jobs-service-inmemory</artifactId>
        </dependency>
        <!-- Jobs Management endpoints -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kogito-addons-quarkus-jobs-management</artifactId>
        </dependency>
      </dependencies>
    </profile>

    <profile>
      <id>bamoe-audit</id>
      <dependencies>
        <!-- Data Audit -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kogito-addons-quarkus-data-audit-jpa</artifactId>
        </dependency>
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kogito-addons-quarkus-data-audit</artifactId>
        </dependency>
      </dependencies>
    </profile>

    <profile>
      <id>bamoe-kafka-events</id>
      <dependencies>
        <!-- Messaging -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kie-addons-quarkus-messaging</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
        </dependency>
        <!-- Events -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kie-addons-quarkus-events-process</artifactId>
        </dependency>
      </dependencies>
    </profile>

    <profile>
      <id>bamoe-elk-process-monitoring</id>
      <dependencies>
        <!-- Process Monitoring - ELK -->
        <dependency>
          <groupId>org.kie</groupId>
          <artifactId>kie-addons-quarkus-monitoring-elastic</artifactId>
        </dependency>
      </dependencies>
    </profile>

    <profile>
      <id>opentelemetry-traces-logs-metrics</id>
      <dependencies>
        <!-- Logs (ELK) -->
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-logging-gelf</artifactId>
        </dependency>

        <!-- Metrics -->
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-micrometer</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
        </dependency>
        <!--
        <dependency>
          <groupId>io.quarkiverse.micrometer.registry</groupId>
          <artifactId>quarkus-micrometer-registry-otlp</artifactId>
          <version>${micrometer.version}</version>
        </dependency>
        -->

        <!-- Traces -->
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-opentelemetry</artifactId>
        </dependency>
        <dependency>
          <groupId>io.opentelemetry.instrumentation</groupId>
          <artifactId>opentelemetry-jdbc</artifactId>
        </dependency>
        <dependency>
          <groupId>io.opentelemetry.instrumentation</groupId>
          <artifactId>opentelemetry-kafka-clients-2.6</artifactId>
        </dependency>
      </dependencies>
    </profile>

    <profile>
      <id>container</id>
      <properties>
        <quarkus.profile>container</quarkus.profile>
      </properties>
      <dependencies>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-container-image-jib</artifactId>
        </dependency>
      </dependencies>
    </profile>
  </profiles>

  <build>
    <finalName>${project.artifactId}</finalName>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
